### ISSUE TITLE
OG sprites lower quality than previous chapters / Use Hou+ Sprites

### ISSUE THREAD

**Issue by drojf** [07th-mod/higurashi-rei#14]
Currently for Rei we use the low resolution (`640x480`) sprites that come with the unmodded game.

Previous chapters use upscaled versions of these sprites, upscaled to `1280x960` resolution. I don't remember what upscaling we used though, I will have to check git or discord history.

However, there was some discussion whether we could use the high resolution Hou+ sprites for our OG sprites, since those are naturally high resolution (or at least look sharper than upscaled sprites). I'm not sure whether the Hou+ sprites would cover all the sprites we have in the mod, though - I haven't even looked at them myself yet.

So there are two things to be done for this issue, one to make this chapter consistent with previous chapters, and one to overhaul all the OG sprites:
 - [ ] Upscale the existing sprites to fix this issue quickly (or just proceed with below first)
 - [ ] In the long term, use the mapping in https://github.com/drojf/match_higurashi_scripts and the Hou+ sprites to regenerate all the OG sprite packs.

Also see https://github.com/07th-mod/higurashi-rei/issues/10 "OG Sprites / Backgrounds Known Issues"

**Comment by drojf** [comment]
There was some discussion on discord, and basically Apollo from discord is manually replacing the sprites with the Hou+ sprites, and I'm checking them, starting from onikakushi.

Because the original files are being used, I should be able to generate a mapping of Hou+ sprite name -> Mod sprite name, should we ever need to re-process the files.

### TODO

- **Fix https://github.com/07th-mod/minagoroshi/issues/38**, eg double check the eye-cut ins for each chapter

- [ ] Add note that https://github.com/drojf/match_higurashi_scripts sprite mapping is invalid/should no longer be used
- [x] Checking to be done on each sprites
    - [x]  Run through winmerge to check for missing/extra sprites 
    - [x] Visually compare every sprite to make sure it's the same one (use some comparison tool? not sure how to flick through images with Winmerge)
- [x] Save mapping of hou+ sprite name -> mod sprite name
- [x] Check if unusual sprite size will cause any problems in the mod?
- [x] Compress/Optimize all .pngs for final ver?
- [x] Fix sprites with white outlines? 
    - [x] Seems to only affect mion's sprites, but best to generate sprite-on-black to check all USED sprites (don't bother with unused sprites)
- [x] Fix bugged sprites
    - [x] sprite with line through it
    - [x] sprite with interior region not transparent

**Comment by drojf** [comment]
There are some anomalies with the hou+ sprites which I'll log here:

- Because in the original game, the heads were separate from the bodies, the head positions chosen in the Hou+ sprites may differ from our existing sprites
- Some Hou+ sprites for certain characters differ in quality - they look upscaled and not as sharp (put screenshot details below). Usually this is for characters who don't appear very often

For example, this sprite has the head properly processsed, but the body seems upscaled/blurry:
![image](https://github.com/07th-mod/higurashi-rei/assets/1249449/a31b2242-4c1c-468d-8337-7d84eb9e0e05)
