### ISSUE TITLE
Original BGM/SE (GIN BGM/SE) for Rei

### ISSUE THREAD

**Issue by drojf** [07th-mod/higurashi-rei#18]
(names have been abbreviated)

OV on discord has manually produced a BGM/SE pack for Rei, which can be downloaded here: https://drive.google.com/drive/folders/1FSdCu97IE_pF1_S7uQ-S4LZVRtXqYxdh?usp=sharing

> This is where i uploaded the folder, and i didn't use the files from your releases, i used the original tracks from the original release of rei, and K4 helped me convert them to .ogg

It appears no script changes are required for Rei - we can just do a straight file replacement to go back to the OG BGM/SE.

## Description from discord

https://drive.google.com/drive/folders/1FSdCu97IE_pF1_S7uQ-S4LZVRtXqYxdh?usp=sharing

> okay so i played through all of Saikoroshi and the beginnings of Hirukowashi and Batsukoishi to make sure it works, so for those who want, you can now play rei with the original BGM and SE! just download both folders and drag to replace all files in the BGM and SE folders respectively.
> just make sure to backup the current folders if you want to keep the option to play with the new bgm/se
> 
> (note: console hirukowashi will still play the console ost)
> 
> thanks to K4 for helping me convert all the necessary files
> and this should work in both modded and unmodded versions of rei
> K4 — 08/27/2022 2:39 AM
> Good job. Did you do any comparisons of their placement as well?
> OV — 08/27/2022 2:40 AM
> i did some comparisons and timings seem to be exactly the same, but obviously i didn't check every scene in all arcs 
> K4 — 08/27/2022 2:40 AM
> That's good to hear.
> It's worth noting that I simply converted all the files OV gave me to OGG. Many of them were MP3s, so their quality was already not great and got further reduced by the conversion. Many of these files have already existed in the OGG format in MG's earlier releases. If those were converted from lossless sources rather than MP3s, their quality should be better. I wouldn't count on it though. If they also converted them from MP3 and WAV, my own conversions might actually be of superior quality, since I picked the highest possible bitrate. 
> 
> 

##  Regarding the filename difference between the OG game and Mangagamer's release

No they weren't the same
Between the original rei and steam rei some of the names are different, don't remember the amount i had to change because i did it back when it released
The timings are also exactly the same as the original rei release
I think the thing i needed to change the most were the sound effects, because the names were completely different
I basically had to listen to each one and know which replaces which

## Regarding the console chapters

> I played console hirukowashi and the console music was exactly the same since it uses different files, for the effects i dont remember but basically everything you added from console is untouched, while everything else is the original bgm/se

So we don't need to add any special cases so that the console chapters use the console BGM.

## TODO

- [x] Try to figure out the BGM/SE mapping
- [x] Validate the BGM/SE choices are correct
- [x] Generate BGM name mapping
- [x] Upload BGM files
- [x] Update installer version for Rei BGM pack
- [x] Generate new Rei release
- [x] Update wiki (push commit)

**Comment by drojf** [comment]
So to summarize what I did:

- Did some unnecessarily complicated checks to double check that the nscripter Rei and mangagamer Rei's BGM/SE are consistent with their filenames. As far as I can tell they are consistent (none of the bgm/se have been swapped around or anything like that). This means that we can assume the Rei BGM names refer to the same files always as the Mangagamer Rei, and no script changes are necessary.
- Went through the BGM/SE and checked which ones are different from Mangagamer, and also corrected for any slight differences in filename. See the "Rei Mapping" sheet here: https://docs.google.com/spreadsheets/d/1CzZ6IBOPmDozdatWM2rol1DR2xjIaySSKY5XQV4yhdI/edit?usp=sharing
    - Most of the Mangagamer Rei BGM are exactly the same as the original release
        - All of the different 'music' tracks can be taken from our previous GIN BGM releases
        - The different background SFX (like sound of rain) can't be taken from the GIN SE release
    - Many of the Mangagamer Rei SE are different from the original release (they have tried to replace them with similar sounding SE)
- Using the above BGM/SE mapping, I built a BGM pack by either copying our existing GIN BGM files, or transcoding to .ogg from the original JP Rei release
- I cross checked this pack against what OV on discord gave me, and they were the same except:
    - OV's files have capitalization the same as the Original JP Rei release, but for the files to work correctly on Linux they must be all lowercase. I use exactly the same names as the original game, which should be all lowercase
    - When re-encoding, I made sure that the output format was always -q5 (~160kbps), 44100 hz, 2 channels, as some files are in lower sampling rate or only 1 channel which the engine may not like
    - OV has included all BGM/SE, but I've only included the ones which were different. 
 

This produced this BGM pack: https://1drv.ms/u/s!Ar-lAVeetlqhhMF8MlPpm6Ls3atv9w?e=yG8Or3

Later I'll double check this and include it in the installer.

**Comment by drojf** [comment]
GIN BGM / OG BGM should now be live in the installer
