### ISSUE TITLE
OG Sprites / Backgrounds TODO

### ISSUE THREAD

**Issue by drojf** [07th-mod/higurashi-rei#9]
## TODO

- [X] ~~Fix sprite generation script~~ to take into account that sometimes the lipsync variants (with _0, _1, and _2 suffixes) are used. ~~Need to duplicate the lipsync variants which are used~~
  - [X] This should actually be fixed in the DLL - maybe some change on Rei made it so it doesn't automatically look up the _0 variant for non-console sprites when the _1 or _2 variant is requested? 
- [X] Fix problem on Rei where characters stand outside the 4:3 window (especially on saikoroshi). Not sure if this is easily fixable           

    - [X] could move characters like in previous chapters to their 'original' squished together positions. Alternatively, tell users they should enable stretch mode for saikoroshi

- [X] Detect/fix sprites which should be replaced with `transparent.png`

- [X] Manually fix some effect backgrounds not being replaced (easier to just run through the chapter and fix bugs as we see them, or copy from previous chapter)

- [x] Optimize all images using `ect -9`
- [x] Notify CGALt creator of DLL changes
- [x] Create new release with script and DLL changes, and re-test briefly

**Comment by drojf** [comment]
og sprites and backgrounds are released!
